.github/workflows/push-trigger.yml

chore(INJI-455) - Add qa-develop branch in workflow

Support qa-develop branch in workflow

---

.github/workflows/push-trigger.yml

added push trigger for injiweb-1 for docker image

added push trigger for injiweb-1

---

Dockerfile
src/main/resources/bootstrap.properties

Reverting the properties to the previous values

Reverted the bootstrap.properties to the previous values

---

src/main/java/io/mosip/mimoto/service/impl/V2IssuersServiceImpl.java

Signed-off-by: Shiva <shivakumar@beehyv.com>

Update pdf properties while generating the Certificate

---

src/main/java/io/mosip/mimoto/service/impl/V2IssuersServiceImpl.java

Signed-off-by: Shiva <shivakumar@beehyv.com>

Updated the display name in the pdf properties

---

pom.xml
src/main/java/io/mosip/mimoto/controller/IssuersController.java
src/main/java/io/mosip/mimoto/dto/mimoto/CredentialDefinitionResponseDto.java
src/main/java/io/mosip/mimoto/dto/mimoto/CredentialDisplayResponseDto.java
src/main/java/io/mosip/mimoto/dto/mimoto/CredentialIssuerDisplayResponse.java
src/main/java/io/mosip/mimoto/dto/mimoto/CredentialIssuerWellKnownResponse.java
src/main/java/io/mosip/mimoto/dto/mimoto/CredentialSupportedDisplayResponse.java
src/main/java/io/mosip/mimoto/dto/mimoto/CredentialsSupportedResponse.java
src/main/java/io/mosip/mimoto/dto/mimoto/IssuerSupportedCredentialsResponse.java
src/main/java/io/mosip/mimoto/dto/mimoto/VCCredentialDefinition.java
src/main/java/io/mosip/mimoto/dto/mimoto/VCCredentialIssueBody.java
src/main/java/io/mosip/mimoto/dto/mimoto/VCCredentialProperties.java
src/main/java/io/mosip/mimoto/dto/mimoto/VCCredentialRequest.java
src/main/java/io/mosip/mimoto/dto/mimoto/VCCredentialRequestProof.java
src/main/java/io/mosip/mimoto/dto/mimoto/VCCredentialResponse.java
src/main/java/io/mosip/mimoto/dto/mimoto/VCCredentialResponseProof.java
src/main/java/io/mosip/mimoto/exception/PlatformErrorMessages.java
src/main/java/io/mosip/mimoto/service/IssuersService.java
src/main/java/io/mosip/mimoto/service/impl/IssuersServiceImpl.java
src/main/java/io/mosip/mimoto/util/JoseUtil.java
src/main/java/io/mosip/mimoto/util/RestApiClient.java
src/main/java/io/mosip/mimoto/util/Utilities.java
src/main/resources/application-local.properties
src/main/resources/templates/CredentialTemplate.html
src/main/resources/wellKnownIssuer/Insurance.json
src/test/java/io/mosip/mimoto/controller/InjiControllerTest.java
src/test/java/io/mosip/mimoto/service/IssuersServiceTest.java

- removed flying saucer library and used itext for pdf rendering
- implemented custom file name for pdf
- removed v2 changes and merged to existing controller

[INJIWEB-43] refractored v2 apis to existing controller

---

apitest/pom.xml
apitest/testNgXmlFiles/mimotoApi.xml

Migrated mimoto api automation test suite to Java21.

MOSIP-32363

---

apitest/pom.xml
apitest/testNgXmlFiles/mimotoApi.xml

Reverting JAVA 21 upgrade from develop branch as JAVA 21 upgraded code will be pushed to new branch "develop-java21".

MOSIP-32363 Java 21 revert

---

apitest/src/main/resources/mimoto/WalletBinding/WalletBinding.yml

INJIMOB-1345 | Fixes for automation failures

MOSIP-33136

---

src/main/java/io/mosip/mimoto/util/Utilities.java
src/main/resources/application-local.properties
src/main/resources/bootstrap.properties
src/main/resources/mimoto-issuers-config.json
src/main/resources/templates/CredentialTemplate.html

To start mimoto locally,
- replace mosip.esignet.host by local esignet host url 
- use your own client id and p12 file

start mimoto locally with sunbird credential

---

apitest/src/main/resources/config/Kernel.properties

Updating the kernel properties

INJIMOB-1593

---

apitest/src/main/java/io/mosip/testrig/apirig/testrunner/MosipTestRunner.java

Updated the comments for generating biometric details with mock mds

MOSIP-35107 - Updated the biometric details w.r.t mock mds java21

---

src/main/java/io/mosip/mimoto/dto/mimoto/CredentialsSupportedResponse.java
src/main/java/io/mosip/mimoto/dto/mimoto/ProofTypesSupported.java
src/main/java/io/mosip/mimoto/util/CredentialIssuerWellknownResponseValidator.java
src/test/java/io/mosip/mimoto/util/CredentialIssuerWellknownResponseValidatorTest.java
src/test/java/io/mosip/mimoto/util/TestUtilities.java
src/test/resources/responses/expectedWellknown.json

- Modify well known response DTO to accomodate changes for mso_mdoc VC
- Add validations for wellknown response based on VC formats

[INJIMOB-1078] add support for wellknown response of mso_mdoc VC format

---

api-test/src/main/resources/config/mimoto.properties

MOSIP-36077 - Added actuator property

MOSIP-36077 - Added actuator property

---

api-test/README.md
api-test/pom.xml
api-test/src/main/java/io/mosip/testrig/apirig/mimoto/testrunner/MosipTestRunner.java
api-test/src/main/java/io/mosip/testrig/apirig/mimoto/testscripts/SimplePost.java
api-test/src/main/java/io/mosip/testrig/apirig/mimoto/testscripts/SimplePostForAutoGenId.java
api-test/src/main/java/io/mosip/testrig/apirig/mimoto/utils/MimotoConfigManager.java
api-test/src/main/java/io/mosip/testrig/apirig/mimoto/utils/MimotoUtil.java
api-test/src/main/resources/config/mimoto.properties
api-test/src/main/resources/mimoto/DownloadIssuerCredential/DownloadIssuerCredential.yml

MOSIP-38392 - Merged apitest from develop with release branch

MOSIP-38392 - Merged apitest from develop with release branch

---

docker-compose/config/mimoto-issuers-config.json
docs/api-documentation-openapi.json
src/main/java/io/mosip/mimoto/config/IssuersValidationConfig.java
src/main/java/io/mosip/mimoto/dto/IssuerDTO.java
src/main/java/io/mosip/mimoto/service/impl/IssuersServiceImpl.java
src/main/resources/mimoto-issuers-config.json
src/test/java/io/mosip/mimoto/controller/IssuersControllerTest.java
src/test/java/io/mosip/mimoto/util/TestUtilities.java

Add Credential Issuer Host in IssuerDTO

[INJIMOB: 2452]: Add Credential Issuer Host in IssuerDTO 

---

docker-compose/config/mimoto-issuers-config.json
src/main/java/io/mosip/mimoto/dto/IssuerDTO.java
src/main/resources/mimoto-issuers-config.json
src/test/java/io/mosip/mimoto/controller/IssuersControllerTest.java
src/test/java/io/mosip/mimoto/util/TestUtilities.java

[INJIMOB-2452]: Add Credential Issuer Host

---

api-test/README.md
api-test/pom.xml
docker-compose/config/mimoto-issuers-config.json
docs/api-documentation-openapi.json
pom.xml
src/main/java/io/mosip/mimoto/config/IssuersValidationConfig.java
src/main/java/io/mosip/mimoto/dto/IssuerDTO.java
src/main/java/io/mosip/mimoto/service/impl/IssuersServiceImpl.java
src/main/resources/mimoto-issuers-config.json
src/test/java/io/mosip/mimoto/controller/IssuersControllerTest.java
src/test/java/io/mosip/mimoto/util/TestUtilities.java

Add Issuer ID and Credential Issuer Host fields for wellknown discovery

[INJIMOB-2452]: Add Issuer ID and Credential Issuer Host fields.

---

pom.xml
src/main/java/io/mosip/mimoto/controller/IdpController.java
src/main/java/io/mosip/mimoto/controller/IssuersController.java
src/main/java/io/mosip/mimoto/exception/PlatformErrorMessages.java
src/main/java/io/mosip/mimoto/util/Utilities.java
src/test/java/io/mosip/mimoto/controller/IdpControllerTest.java
src/test/java/io/mosip/mimoto/controller/IssuersControllerTest.java
src/test/java/io/mosip/mimoto/controller/VerifiersControllerTest.java
src/test/java/io/mosip/mimoto/service/CredentialServiceTest.java
src/test/java/io/mosip/mimoto/service/CredentialShareServiceTest.java
src/test/java/io/mosip/mimoto/service/IdpServiceTest.java
src/test/java/io/mosip/mimoto/service/IssuersServiceTest.java
src/test/java/io/mosip/mimoto/util/TestUtilities.java
src/test/resources/responses/expectedIssuerConfig.json

- Added test cases for newly added or update code in the below files:
CredentialServiceImpl, IdpController, IdpServiceImpl, VerifiersController

[Injiweb 1429] add test cases for newly added code

---

docs/api-documentation-openapi.json
docs/postman-collections/MIMOTO.postman_collection.json

- Add info about new issuer configuration endpoint in mimoto postman collections and update params list for credentials download endpoint

[INJIWEB-1429] update mimoto postman collection and open api json file

---

pom.xml
src/main/java/io/mosip/mimoto/controller/SessionController.java
src/main/java/io/mosip/mimoto/controller/UserController.java
src/main/java/io/mosip/mimoto/util/Utilities.java
src/main/resources/application-local.properties
src/test/java/io/mosip/mimoto/controller/SessionControllerTest.java
src/test/java/io/mosip/mimoto/controller/UserControllerTest.java
src/test/java/io/mosip/mimoto/security/oauth2/OAuth2AuthenticationSuccessHandlerTest.java
src/test/java/io/mosip/mimoto/security/oauth2/OAuth2LoginTests.java

- Written test cases for the wallet endpoints in the user controller.
- Updated the google authorization endpoint config to show the consent popup for the selected account only if the consent i s not given before for the same account.
- Updated the session controller and user controller endpoints to return the response without the response wrapper and updated the test cases for the same.

[Injiweb 1370] login feature enhancements

---

docs/api-documentation-openapi.json
src/main/java/io/mosip/mimoto/controller/UsersController.java
src/main/java/io/mosip/mimoto/exception/DatabaseConnectionException.java
src/main/java/io/mosip/mimoto/exception/PlatformErrorMessages.java
src/test/java/io/mosip/mimoto/controller/UsersControllerTest.java
src/test/java/io/mosip/mimoto/controller/WalletCredentialsControllerTest.java

- Added details about all the endpoints that were added as part of login flow
- Updated few error messages and error codes

[Injiweb 1418] add info about login endpoints in openapi documentation json file

---

api-test/src/main/java/io/mosip/testrig/apirig/mimoto/utils/MimotoConstants.java
api-test/src/main/java/io/mosip/testrig/apirig/mimoto/utils/MimotoUtil.java
api-test/src/main/resources/config/mimoto.properties
api-test/src/main/resources/mimoto/OAuthDetailsRequest/OAuthDetailsRequest.yml
api-test/src/main/resources/mimoto/SunBirdC/AuthenticateUserSunBirdC/AuthenticateUserSunBirdC.yml
api-test/src/main/resources/mimoto/SunBirdC/OAuthDetailsRequestSunBirdC/OAuthDetailsRequestSunBirdC.yml
api-test/src/main/resources/mimoto/WalletBinding/WalletBinding.yml

MOSIP-41751 - Fix the mimoto failure testcases which is due to esignet 1.5.1 compatibility
Added the allowed error codes for both esignet 151 and lower versions

MOSIP-41751 - Fix the mimoto failure testcases which is due to esignet 1.5.1 compatibility

---

api-test/pom.xml

MOSIP-41751 - Updated the POM version for the patch release-0.17.1

MOSIP-41751 - Updated the POM version for the patch release-0.17.1

---

api-test/pom.xml
api-test/src/main/resources/mimoto/LoginFlow/DownloadMosipIssuerCredential/DownloadIssuerCredential/DownloadIssuerCredential.yml
api-test/src/main/resources/mimoto/LoginFlow/DownloadMosipIssuerCredential/FetchAllCredentials/FetchAllCredentials.yml
api-test/src/main/resources/mimoto/LoginFlow/DownloadMosipIssuerCredential/ViewCredential/ViewCredential.yml
api-test/src/main/resources/testCaseSkippedList.txt

- Added known failures to the KI bucket.
- Changed the testcase expected errorcode and test case name

INJIWEB-1630 - Fixed automation failures

---

api-test/src/main/resources/mimoto/BindingOtp/BindingOtp.yml

- Changed the error code after the fix from mimoto end.

INJIWEB-1632 - Binding otp validation issue in automation post mimoto fix

---

src/main/resources/application-default.properties

issuersWithSingleVcLimit holds only Mosip

[INJIWEB-1607] update issuersWithSingleVcLimit prop

---

api-test/src/main/resources/testCaseSkippedList.txt

INJIWEB-1666 - Moving the testcases to known issues
-->
Mimoto_BindingOtp_Valid_vid_All_Smoke
Mimoto_WalletBinding_vid_OTP_Valid_Smoke

INJIWEB-1666 - Moving the testcases to known issues

---

src/main/java/io/mosip/mimoto/service/impl/PresentationServiceImpl.java

injiweb-1579 removed list of list in context

injiweb-1579 removed list of list in context

---

.talismanrc
docs/api-documentation-openapi.json
docs/postman-collections/MIMOTO.postman_collection.json

- Add Postman collection entry for the new get matching credentials endpoint
- Include example responses and error scenarios

[INJIWEB-1711] - Update OpenAPI specification with complete endpoint documention

---

.talismanrc
docs/api-documentation-openapi.json
docs/postman-collections/MIMOTO.postman_collection.json

- Add Endpoint in Postman Collection
- Add example responses and scenarios

[INJIWEB-1712] - Add Open API specification for Submit Presentation Endpoint

---

src/main/java/io/mosip/mimoto/service/impl/CredentialMatchingServiceImpl.java
src/test/java/io/mosip/mimoto/service/CredentialMatchingServiceTest.java

- Replace custom DTOs with official OpenID4VP library classes
- Update CredentialMatchingServiceImpl to use PresentationDefinition, InputDescriptor, Constraints, Fields, and Filter from io.mosip.openID4VP
- Simplify presentation definition extraction by using direct object access instead of manual JSON parsing
- Update test classes to use new OpenID4VP library constructors and methods

[INJIWEB-1711] - Migration from Custom Objects to Library Objects

---

api-test/README.md

1. updated version numbers to 0.19.2 for the release

MOSIP-43258 readMe update for the mimoto apitest release 0.19.2
